# configs.py

DEFAULT_STRUCTURE = [8, 32, 16, 4]  # 默认网络结构

# GP 超参数
DEFAULT_POP_SIZE = 50
DEFAULT_N_GENERATIONS = 100
DEFAULT_EPISODES_PER_INDIVIDUAL = 3
DEFAULT_ELITE_FRACTION = 0.2
DEFAULT_MUTATION_RATE = 0.05
DEFAULT_MUTATION_SCALE = 0.1
DEFAULT_SELECTION_K = 3

# early stopping
EARLY_STOPPING_PATIENCE = 10
EARLY_STOPPING_MIN_DELTA = 1.0

# 多进程并发数
DEFAULT_NUM_WORKERS = 4

# 文件路径
CHECKPOINT_PATH = "checkpoint/state.pkl"
BEST_MODEL_PATH_TEMPLATE = "checkpoint/gen_{gen}_best.pt"
FINAL_MODEL_PATH = "checkpoint/final_best.pt"
