# configs.py

# WINDOW 参数
WINDOW_SIZE = 10
STATE_DIM = 8
ACTION_DIM = 4

DEFAULT_STRUCTURE = [WINDOW_SIZE * (STATE_DIM + ACTION_DIM), 64, 32, ACTION_DIM]

# GP 超参数
DEFAULT_POP_SIZE = 500
DEFAULT_N_GENERATIONS = 500
DEFAULT_EPISODES_PER_INDIVIDUAL = 3
DEFAULT_ELITE_FRACTION = 0.2
DEFAULT_MUTATION_RATE = 0.05
DEFAULT_MUTATION_SCALE = 0.1
DEFAULT_SELECTION_K = 3

# early stopping
EARLY_STOPPING_PATIENCE = 20
EARLY_STOPPING_MIN_DELTA = 0.0

# 多进程并发数
DEFAULT_NUM_WORKERS = 10

# 文件路径
CHECKPOINT_PATH = "checkpoint/state.pkl"
BEST_MODEL_PATH_TEMPLATE = "checkpoint/gen_{gen}_best.pt"
FINAL_MODEL_PATH = "checkpoint/final_best.pt"
